### ISSUE TITLE
无法设置第一个主题色

### ISSUE THREAD

**Issue by lyroom** [shaobeichen/gradient-theme#10]
![image](https://github.com/user-attachments/assets/0f481eab-d9bb-45ff-88b9-65ae671a557d)
选择第一个主题色就会这样，大佬们这怎么解决，我是ubuntu22.01lts版本

**Comment by shaobeichen** [comment]
是权限问题，在linux上要放到可写位置里面去 https://github.com/shaobeichen/gradient-theme/blob/main/README-zh.md#2-%E6%89%A7%E8%A1%8C-enable-%E5%91%BD%E4%BB%A4%E6%8F%90%E7%A4%BA%E6%B2%A1%E6%9C%89%E6%9D%83%E9%99%90

**Comment by lyroom** [comment]
ok明白了
