### ISSUE TITLE
关于变量区分

### ISSUE THREAD

**Issue by Stitch-1028** [shaobeichen/gradient-theme#11]
渐变色确实很好看，但是可以像one Dark Pro那样 可以对不同定义的变量单曲区分颜色吗，比如const定义的变量是黄色，let定义的变量是红色，函数定义是蓝色，这样很直观的通过颜色区分当前是常量、变量、函数

**Comment by shaobeichen** [comment]
后续看下，是否支持one Dark pro，到时候就会很区分。

举例，它的原理就是基于原主题的基础上，把蓝色改成了蓝绿色渐变，原本该是什么颜色区分还是什么颜色区分，所以只要支持了one Dark pro后，就很符合你的需求了。

**Comment by shaobeichen** [comment]
https://github.com/users/shaobeichen/projects/2
