### ISSUE TITLE
在进行 gradient theme enable 的时候报错发生了系统错误

### ISSUE THREAD

**Issue by jasperdaiyile** [shaobeichen/gradient-theme#16]
命令 "Gradient Theme: Enable Gradient" 导致错误：
发生了系统错误 (EROFS: read-only file system, open 'xxxxxxx')

**Comment by jasperdaiyile** [comment]
并且每次打开vscode的时候，主题都会还原为原来的主题，需要重新在插件中设置主题，下次还是这样的情况

**Comment by shaobeichen** [comment]
没有权限，如果您是 Windows 用户，您可能需要以管理员权限运行 VS Code。对于 Linux 和 Mac 用户，不得将 Code 安装在只读位置，并且您必须具有写入权限。

https://github.com/shaobeichen/gradient-theme/blob/main/README-zh.md#2-%E6%89%A7%E8%A1%8C-enable-%E5%91%BD%E4%BB%A4%E6%8F%90%E7%A4%BA%E6%B2%A1%E6%9C%89%E6%9D%83%E9%99%90
