### ISSUE TITLE
命令 "Gradient Theme: Enable Gradient" 导致错误

### ISSUE THREAD

**Issue by LBy-QHU** [shaobeichen/gradient-theme#2]
命令 "Gradient Theme: Enable Gradient" 导致错误
发生了系统错误 (EPERM: operation not permitted, open 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-sandbox\workbench\workbench.html')

**Comment by shaobeichen** [comment]
如果您是 Windows 用户，您可能需要以管理员权限运行 VS Code。对于 Linux 和 Mac 用户，不得将 Code 安装在只读位置，并且您必须具有写入权限。

我将写到文档注意事项中去。

**Comment by DaiMu-210** [comment]
Linux 具体应该怎么做？

**Comment by shaobeichen** [comment]
> Linux 具体应该怎么做？

@DaiMu-210 尝试下这个

Mac和Linux用户
如果Visual Studio Code不能自行修改，则扩展将无法工作。这些案例包括：
代码文件是只读的，
代码启动时没有修改自身的权限。
您需要通过运行以下命令来声明Visual Studio Code安装目录的所有权：
sudo chown -R $(whoami) "$(which code)"
sudo chown -R $(whoami) /usr/share/code
占位符<Visual Studio代码路径>表示VSCode安装的路径。它通常是：
/MacOS上的应用程序/Visual Studio Code.app/Contents/MacOS/Electron；
/应用程序/Visual Studio代码-Insiders.app/Contents/MacOS/Electron，在MacOS上使用Insiders分支时；
/usr/share/code，在大多数Linux上；
/Arch Linux上的usr/lib/code/或/opt/visional studio代码。
Mac和Linux软件包管理器可能具有自定义的安装路径。请仔细检查您的路径是否正确。
