### ISSUE TITLE
建议对未使用的代码的着色更暗一些，目前开启渐变不容易区分

### ISSUE THREAD

**Issue by kaiwen0627** [shaobeichen/gradient-theme#20]

**Comment by shaobeichen** [comment]
有没有相应的截图，使用哪个主题会出现这样？

**Comment by shaobeichen** [comment]
我现在看了，其实未使用代码会降低透明度，这是vscode的做法，其实和主题关系不大，试了下，如果降得太低，又太低了，如果加上一些波浪线，又觉得占了很多vscode插件的功能，不合适。
