### ISSUE TITLE
vsdoce远程服务器开启渐变色报错

### ISSUE THREAD

**Issue by huddao** [shaobeichen/gradient-theme#21]
![image](https://github.com/user-attachments/assets/8f5fd2ec-8d67-4f04-8eb0-2a9983138e3b)
请问win安装的vscdoe远程linux服务器时候应该怎么设置呢，直接给图中显示的文件夹写入权限就可以吗，或者可否给一个需要添加权限的文件清单，方便手动逐个添加

**Comment by shaobeichen** [comment]
vscode是基于electron的，插件的原理是修改了electron用来显示webview的workbench.html，workbench.html是在vscode安装软件目录下的，为了保险起见，将vscode安装目录及所有子级一整个都给写入权限
