### ISSUE TITLE
添加浅色渐变主题

### ISSUE THREAD

**Issue by 971230** [shaobeichen/gradient-theme#22]
不知道作者有没有兴趣添加浅色渐变主题？由于公司硬件问题，显示器nit不够，黑色主题在办公时候看着就略黑。哈哈，不管怎样感谢作者的作品。

**Comment by shaobeichen** [comment]
其实也有很多同学想要添加浅色渐变主题，我也简单尝试过几款，但发现实际效果其实并不是很理想，还在一款适合渐变的浅色主题

**Comment by 971230** [comment]
😄哈哈，期待一手调教好后的浅色主题哦，感谢
