### ISSUE TITLE
VS Code Insiders enable命令报错

### ISSUE THREAD

**Issue by hanzhizhh** [shaobeichen/gradient-theme#23]
VsCode Insiders中使用enable gradient命令报错，错误信息为找不到目标文件workbench.esm.html，经排查，VsCode Insiders源文件中，无论什么版本，都是workbench.html没有.esm，与VsCode正式版有出入。
![error](https://github.com/user-attachments/assets/982f9568-d2ba-425e-8ffa-276a3c405b57)
![dir](https://github.com/user-attachments/assets/42677e0e-990a-4262-92d6-eba1bd1a0164)

**Comment by hanzhizhh** [comment]
> 1.94版本以上就是esm了，你的版本是多少 这是我单独下载的版本 Version: 1.94.0-insider (system setup) Commit: 8d1bb84a183d8a4eb74c12ec11c0c5080a548547 Date: 2024-09-19T05:04:09.996Z Electron: 30.5.0 ElectronBuildId: 10198947 Chromium: 124.0.6367.243 Node.js: 20.16.0 V8: 12.4.254.20-electron.0 OS: Windows_NT x64 10.0.19045
1.95 可能是因为版本是user-setup
![vsc-i-info](https://github.com/user-attachments/assets/d4964604-0378-466d-beb2-cf5985ea46b8)

**Comment by hanzhizhh** [comment]
1.95 user-setup
![vsc-i-info](https://github.com/user-attachments/assets/e48918e7-7c21-4e7c-8b8b-4b0cfb245e95)

**Comment by shaobeichen** [comment]
vscode他们可真搞人，1.94以下是workbench，1.94是workbench.esm，1.94以上又改回来了.....我真是....一会更新一版

**Comment by fy0110** [comment]
版本: 1.94.1 (system setup)
提交: e10f2369d0d9614a452462f2e01cdc4aa9486296
日期: 2024-10-05T05:44:32.189Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100

1.94.1 还是esm的

**Comment by shaobeichen** [comment]
> 版本: 1.94.1 (system setup) 提交: e10f2369d0d9614a452462f2e01cdc4aa9486296 日期: 2024-10-05T05:44:32.189Z Electron: 30.5.1 ElectronBuildId: 10262041 Chromium: 124.0.6367.243 Node.js: 20.16.0 V8: 12.4.254.20-electron.0 OS: Windows_NT x64 10.0.26100
> 
> 1.94.1 还是esm的

OK，下版本修复下
