### ISSUE TITLE
启用渐变色后颜色显示不正确

### ISSUE THREAD

**Issue by code-leitianshuo** [shaobeichen/gradient-theme#27]
### What is the problem you encountered? What actually happened? What is the performance? / 你遇到的问题是什么？实际发生了什么？表现是什么？

![微信图片_20241010184901](https://github.com/user-attachments/assets/7edb5906-7a44-48bd-a63f-fc562fa11a5a)
使用"Gradient Bearded Theme Arc"主题并启用"Gradient Theme : Enable Gradient"之后应该启用渐变的字体出现无法正常显示的情况

### plugin version / 插件版本

1.11.2

### System Info / 系统信息

Windows11

### VSCode Info / VSCode信息

![image](https://github.com/user-attachments/assets/ff7be166-234a-4b12-9842-535e58a320c8)

**Comment by shaobeichen** [comment]
你是不是没切换主题，我看还有发光？主题里没有发光的功能

**Comment by code-leitianshuo** [comment]
切换主题了，但是还是这样，我再看看吧，可能是冲突了
