### ISSUE TITLE
请求加上对id选择器的渐变支持效果

### ISSUE THREAD

**Issue by mateboys** [shaobeichen/gradient-theme#30]
### Function Description / 功能描述

目前看id选择器是没有渐变效果的
![image](https://github.com/user-attachments/assets/7d219b77-1cc7-47f3-9a63-59c40f5ed45c)

**Comment by shaobeichen** [comment]
是这样的，在主题设计渐变时也会有一个隐藏设计规范，不是对所有的文本都会有渐变效果，那样看起来就会显得很乱，所以一个主题，最多两种标签有渐变。
