### ISSUE TITLE
希望能够支持webStorm

### ISSUE THREAD

**Issue by ran-the-moon** [shaobeichen/gradient-theme#32]
### Function Description / 功能描述

如果能够支持**webStorm**的话，希望能够增加**MaterialThemeUl**（插件）下的 **SandyBeach**主题
浅色主题示例：
![6e0cb6dfbac0adce8c8baabf0260a2a](https://github.com/user-attachments/assets/35265ee9-7edc-4842-813b-4a5ff9a15a70)

**Comment by ran-the-moon** [comment]
![6e0cb6dfbac0adce8c8baabf0260a2a](https://github.com/user-attachments/assets/9fdae5d4-be88-4ce8-847f-5f1156f68cf7)

**Comment by shaobeichen** [comment]
好的，后续查看下
