### ISSUE TITLE
标点符号的颜色可以加深点吗

### ISSUE THREAD

**Issue by chenjunup** [shaobeichen/gradient-theme#33]
### Function Description / 功能描述

标点的颜色和后面ai提示的颜色基本一致，很多时候我都区分不出来末尾是我实际输入的符号，还是ai提示的内容。
希望能区分下标点的颜色和ai提示的颜色
图1是开启渐变主题的效果
图2是未开启渐变主题的效果
![image](https://github.com/user-attachments/assets/18cca2d6-e125-4f7b-a1e4-debc61bbfa39)
![image](https://github.com/user-attachments/assets/ef241df7-67b0-4f00-b2b7-677e0d1afa46)

**Comment by shaobeichen** [comment]
我看了下 Bearded theme arc 主题的逗号，颜色为rgba(208,215,228,0.38)，渐变开启前和开启后的颜色都是一样的，原主题也是这样的颜色
