### ISSUE TITLE
大佬，可否制作webstorm版本的插件？

### ISSUE THREAD

**Issue by lvjisong** [shaobeichen/gradient-theme#37]
### What is the problem you encountered? What actually happened? What is the performance? / 你遇到的问题是什么？实际发生了什么？表现是什么？

vscode版本已经安装了，webstorm也想实现这样的效果

### plugin version / 插件版本

1.13.0

### System Info / 系统信息

Mac

### VSCode Info / VSCode信息

1.95.3 (Universal)

**Comment by shaobeichen** [comment]
还在研究webstorm的渐变插件怎么写哈哈，要等等
