### ISSUE TITLE
提供浅色主题或不依赖内置主题且灵活动态的配置项

### ISSUE THREAD

**Issue by zhe-qi** [shaobeichen/gradient-theme#38]
### Function Description / 功能描述

例如依靠编辑器标记和作用域和渐变的css样式，可以做到对编辑器标记和作用域进行渐变样式的覆盖。
由于我使用的是浅色系主题和磨砂玻璃背景，并没有在内置主题中找到浅色主题。

**Comment by zhe-qi** [comment]
![image](https://github.com/user-attachments/assets/3f308f32-bbe1-412a-88c4-55516475df45)
这是我目前的主题效果

**Comment by zhe-qi** [comment]
![image](https://github.com/user-attachments/assets/7bfe817f-43a8-4d04-84f1-d31c5f967b6c)
这是我目前的主题效果

**Comment by zhe-qi** [comment]
![image](https://github.com/user-attachments/assets/b732971a-6b40-4bc2-ac0f-74dabb60a060)
我目前主题的效果

**Comment by shaobeichen** [comment]
其实我也一直寻找一款适合渐变色的浅色主题，但是没找到，如果你需要自由配置的话，目前已经支持了，可以看下文档

**Comment by zhe-qi** [comment]
文档描述的很模糊，尤其是关于css编写那一块，可以提供css编写示例或相关文档吗

**Comment by shaobeichen** [comment]
视频教学文档在这里。https://github.com/shaobeichen/gradient-theme/blob/main/README-zh.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A2%98
