### ISSUE TITLE
vscode用vim扩展，vin光标有时失踪

### ISSUE THREAD

**Issue by wu144053** [shaobeichen/gradient-theme#6]
vscode使用vim插件时有时候光标会消失，比如当光标移动到等号时视频给了
![微信截图_20240919215636](https://github.com/user-attachments/assets/56e3a960-5e75-44d9-9d70-07eba5def9eb)

https://github.com/user-attachments/assets/29725509-c71d-40a8-94ed-aed0d3f2040a

**Comment by shaobeichen** [comment]
已经复现，会在1.8.0版本发布

**Comment by wu144053** [comment]
1.8.0版本光标好像还是会消失
![image](https://github.com/user-attachments/assets/e021ce9c-7151-49f9-bba6-3d35c2cf75fe)

https://github.com/user-attachments/assets/be464bb7-7fec-49ee-b023-873db8cbe1cc

**Comment by shaobeichen** [comment]
更新之后，需要重新执行下命令 @wu144053
