### ISSUE TITLE
按教程未报错，但.py .cpp无效果

### ISSUE THREAD

**Issue by CrazyBullets** [shaobeichen/gradient-theme#7]
我安装教程下载了插件，选择了主题，然后enable了主题，但是python文件没有渐变效果，切换到cpp文件中也没有效果，大佬是只能在html文件中使用吗？

**Comment by tenauge** [comment]
不会吧，py文件我是有效果的

**Comment by shaobeichen** [comment]
python和cpp要安装自己的语法插件，比如cpp要安装 C/C++类似的语法插件，python要安装python类似的语法插件，才能识别相应的语法，否则只能一律被当做普通文本。

**Comment by CrazyBullets** [comment]
@shaobeichen 大佬，我确实装了，平常用的是cpp和py， C/C++  python pylance等那些插件确实都装了

![图片](https://github.com/user-attachments/assets/fb261cc1-75b5-4a43-8fcf-4e7cd8df76f3)
操作步骤：1.安装插件 2.选中gradient 中的任意一个主题 3.restart 4.gradient enable

**Comment by CrazyBullets** [comment]
@shaobeichen 大佬，我在另一台电脑上正常配置成功了，疑似是我自己配置过的setting.json或其他我自己的原因 我自己琢磨一下，再问问大佬能适配 Eva Theme系列嘛

**Comment by shaobeichen** [comment]
好的，我记下了，后续安排
